load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

licenses(["notice"])

cc_binary(
    name = "scaling_doubles",
    srcs = glob([
        "*.cpp", 
        "*.h",
    ]),
    deps = ["//third_party/fruit"],
)
